apiVersion: batch/v1
kind: Job 
metadata:
 name: example-job
spec: 
  completions: 1
  parallelism: 1
  template: 
   spec:
     containers: 
     - name: job-container
       image: busybox
       command: ["echo", "Hello, Kubernetes!"]
     restartPolicy: Never
